#!/usr/bin/env bash

readonly USER="thynkon"

readonly HOSTNAME_FILE="/etc/hostname"
readonly HOSTNAME="fedora"

readonly FEDORA_VERSION=$(rpm -E %fedora)

readonly DNF_CONFIG="/etc/dnf/dnf.conf"
readonly RPM_FUSION="https://download1.rpmfusion.org"
readonly RPM_FUSION_FREE="$RPM_FUSION/free/fedora/rpmfusion-free-release-$FEDORA_VERSION.noarch.rpm"
readonly RPM_FUSION_NONFREE="$RPM_FUSION/nonfree/fedora/rpmfusion-nonfree-release-$FEDORA_VERSION.noarch.rpm"

readonly SOFTWARE_FILE="software"
readonly CODECS_FILE="codecs"
readonly FONTS_FILE="fonts"

export readonly GITHUB="https://github.com"
export readonly GITHUB_USERNAME="Thynkon"

#TODO
# check if deltarpm and fastestmirror are already in dnf config file

echoerr() {
	echo "$@" 1>&2
}

install_packages() {
	packages_list=""

	while IFS= read -r line; do
		packages_list+=$line"  "
	done < "$1"

	dnf install $packages_list
}

change_hostname() {
	# Change hostname
	if [[ -z $HOSTNAME ]];then
		echoerr "Hostname is null\n"
	fi

	echo $HOSTNAME >> $HOSTNAME_FILE
	hostname $HOSTNAME
}

setup_dotfiles() {
	# Setup dotfiles
	git clone --bare "$git@github.com:$GITHUB_USERNAME/dotfiles.git" "$HOME/dev/dotfiles"

	if [[ $? -eq 1 ]]; then
		echoerr "Failed to clone dotfiles repository!\n"
		echoerr "Check your ssh keys!\n"

		exit 1
	fi

	git --git-dir=$HOME/dev/dotfiles/ --work-tree=$HOME checkout -f
	git --git-dir=$HOME/dev/dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
}
export -f setup_dotfiles

setup_zsh() {
	local ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"

	# Oh-my-zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

	# powerlevel
	git clone $GITHUB/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k

	### Plugins
	# alias-tips
	git clone $GITHUB/djui/alias-tips.git $ZSH_CUSTOM/plugins/alias-tips

	# zsh-completions
	git clone $GITHUB/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions

	# zsh-syntax-highlighting
	git clone $GITHUB/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
}
export -f setup_zsh

main() {
	change_hostname

	# Improve dnf speed
	echo "fastestmirror=1" >> $DNF_CONFIG
	echo "deltarpm=1" >> $DNF_CONFIG

	# Enable rpmfusion repositories
	dnf install -y $RPM_FUSION_FREE $RPM_FUSION_NONFREE
	dnf update

	# Install software, codecs and fonts
	install_packages $SOFTWARE_FILE
	install_packages $CODECS_FILE
	install_packages $FONTS_FILE
	wget "$GITHUB/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraMono/Regular/complete/Fura%20Mono%20Regular%20Nerd%20Font%20Complete.otf" -P /home/$USER/Downloads

	# Install oh-my-zsh, powerlevel10k and some zsh plugins
	su $USER -c "bash -c setup_zsh"
	setup_zsh

	su $USER -c "bash -c setup_dotfiles"
	ln -s /home/$USER/.p10k.zsh /root/

	# Vundle, vim's plugin manager
	su $USER -c "git clone $GITHUB/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"
}

main

exit 0
