#!/usr/bin/env bash

CURRENT_DIR=$(pwd)
PATH="${CURRENT_DIR}:${PATH}"
PATH="${CURRENT_DIR}/lib:${PATH}"
PATH="${CURRENT_DIR}/scripts:${PATH}"
export PATH

source "config.sh"
source "lib.sh"
source "vscode.sh"

user="thynkon"
hostname="fedora"
mode="desktop"

confirm=n

declare -A installation_info
installation_info[user]="${user}"
installation_info[hostname]="${hostname}"
installation_info[mode]="${mode}"

# Exits on error
set -e

main() {
	if [ $EUID -ne 0 ]; then
		echo "You must execute this script as root!"
		exit 1
	fi

	while getopts "h:m:u:" option; do
		case "${option}" in
			h)
				hostname=$OPTARG
				;;

			m)
				mode=$OPTARG
				;;

			u)
				user=$OPTARG
				;;

			*)
				usage
				exit 1
				;;

		esac
	done

	if [ "$mode" = "laptop" ]; then
		hostname+="-laptop"
	fi

	get_installation_info

	read -p  "Continue? y/n:"  confirm
	if [[ "$confirm" != "y" ]]; then
		echo "Exiting..."
		exit 0
	fi

	dnf.sh
	change_hostname

	# Install software, codecs and fonts
	install_packages "${COMMON_SOFTWARE}"
	
	if [ "$mode" = "dekstop" ]; then
		install_packages $DESKTOP_SOFTWARE
	else
		install_packages $LAPTOP_SOFTWARE
	fi

	install_packages $CODECS_FILE
	install_packages $FONTS_FILE
	su "${user}" -c "fonts.sh"

	# Gitahead
	su "${user}" -c "gitahead.sh"

	# VSCode
	install_vscode
	su "${user}" -c "source vscode.sh; install_vscode_extensions"

	# Install oh-my-zsh, powerlevel10k and some zsh plugins
	su $user -c "zsh.sh"
	"zsh.sh"

	# Install rust
	su $user -c "rust.sh"

	su "${user}" -c "dotfiles.sh"

	if [ -f "/root/.p10k.zsh" ]; then
		rm "/root/.p10k.zsh"
	fi
	ln -s /home/$user/.config/p10k.zsh /root/


	if [ -f "/root/.zshrc" ]; then
		rm "/root/.zshrc"
	fi
	ln -s /home/$user/.zshrc /root/

	su "${user}" -c "neovim.sh"

	if [ "$mode" = "desktop" ]; then
		"monitors.sh"
	fi
}

main $@

exit 0
